### PR TITLE
Allow instance methods to be accessed from the component directly

### PR DESCRIPTION
**Pull request by zachgibb**

### CODE REVIEW

**Comment by cpjolicoeur** [comment]
What is the use case that is requiring this?  Do you have a small gist snippet of the corresponding code that uses these newly exposed instance methods that make them useful?

**Comment by zachgibb** [comment]
This would allow the router to be used within a persistent custom container. This is mainly useful if you want globally accessible navigational components.

For instance, you might want a bottom navigation bar that could be clicked at any time to route to certain component.

``` JSX
class Navigation extends Component {
  settingsRoute() {
    return {
      name: "Settings",
      component: Settings,
    };
  }

  toSettings() {
    this.navComponent.resetToRoute(this.settingsRoute());
  }

  render() {
    return (
      <View>
        <Router
          firstRoute={this.searchRoute()}
          ref={(c) => this.navComponent = c}
        />
        <TouchableHighlight onPress={this.toSettings} >
          <Text> Settings </Text>
        </TouchableHighlight>
      </View>
    );
  }
}
```

It's a bit simplistic, but the "Settings" tab will not disappear when the route changes, and can even change the route itself! This could be used to allow all sorts of more complex navigational structures.

**Comment by zachgibb** [comment]
I have updated this PR to add the methods to the navigation component itself, rather than within the `instanceMethods` layer. *I have updated the example above to reflect this change

**Comment by cpjolicoeur** [comment]
merged for now.  I think we can do a larger refactor, but this is good for now and to not hold up the other project

**Pull request merged**
